# https://docs.netlify.com/configure-builds/file-based-configuration/#configuration-details

[build]
  publish = "examples/svelte/public"
  command = "npm run build && cd examples/svelte && npm install && npm run build"
